// Mocks generated by Mockito 5.3.2 from annotations
// in camera_android_camerax/test/android_camera_camerax_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:camera_android_camerax/src/camera.dart' as _i3;
import 'package:camera_android_camerax/src/camera_info.dart' as _i10;
import 'package:camera_android_camerax/src/camera_selector.dart' as _i12;
import 'package:camera_android_camerax/src/camerax_library.g.dart' as _i2;
import 'package:camera_android_camerax/src/pending_recording.dart' as _i4;
import 'package:camera_android_camerax/src/preview.dart' as _i13;
import 'package:camera_android_camerax/src/process_camera_provider.dart'
    as _i14;
import 'package:camera_android_camerax/src/recorder.dart' as _i6;
import 'package:camera_android_camerax/src/recording.dart' as _i5;
import 'package:camera_android_camerax/src/use_case.dart' as _i15;
import 'package:camera_android_camerax/src/video_capture.dart' as _i16;
import 'package:flutter/foundation.dart' as _i9;
import 'package:flutter/services.dart' as _i8;
import 'package:flutter/src/widgets/framework.dart' as _i7;
import 'package:flutter/src/widgets/notification_listener.dart' as _i17;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResolutionInfo_0 extends _i1.SmartFake
    implements _i2.ResolutionInfo {
  _FakeResolutionInfo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCamera_1 extends _i1.SmartFake implements _i3.Camera {
  _FakeCamera_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePendingRecording_2 extends _i1.SmartFake
    implements _i4.PendingRecording {
  _FakePendingRecording_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRecording_3 extends _i1.SmartFake implements _i5.Recording {
  _FakeRecording_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRecorder_4 extends _i1.SmartFake implements _i6.Recorder {
  _FakeRecorder_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWidget_5 extends _i1.SmartFake implements _i7.Widget {
  _FakeWidget_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i8.DiagnosticLevel? minLevel = _i8.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeInheritedWidget_6 extends _i1.SmartFake
    implements _i7.InheritedWidget {
  _FakeInheritedWidget_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i8.DiagnosticLevel? minLevel = _i8.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeDiagnosticsNode_7 extends _i1.SmartFake
    implements _i9.DiagnosticsNode {
  _FakeDiagnosticsNode_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({
    _i9.TextTreeConfiguration? parentConfiguration,
    _i8.DiagnosticLevel? minLevel = _i8.DiagnosticLevel.info,
  }) =>
      super.toString();
}

/// A class which mocks [Camera].
///
/// See the documentation for Mockito's code generation for more information.
class MockCamera extends _i1.Mock implements _i3.Camera {}

/// A class which mocks [CameraInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockCameraInfo extends _i1.Mock implements _i10.CameraInfo {
  @override
  _i11.Future<int> getSensorRotationDegrees() => (super.noSuchMethod(
        Invocation.method(
          #getSensorRotationDegrees,
          [],
        ),
        returnValue: _i11.Future<int>.value(0),
        returnValueForMissingStub: _i11.Future<int>.value(0),
      ) as _i11.Future<int>);
}

/// A class which mocks [CameraSelector].
///
/// See the documentation for Mockito's code generation for more information.
class MockCameraSelector extends _i1.Mock implements _i12.CameraSelector {
  @override
  _i11.Future<List<_i10.CameraInfo>> filter(
          List<_i10.CameraInfo>? cameraInfos) =>
      (super.noSuchMethod(
        Invocation.method(
          #filter,
          [cameraInfos],
        ),
        returnValue:
            _i11.Future<List<_i10.CameraInfo>>.value(<_i10.CameraInfo>[]),
        returnValueForMissingStub:
            _i11.Future<List<_i10.CameraInfo>>.value(<_i10.CameraInfo>[]),
      ) as _i11.Future<List<_i10.CameraInfo>>);
}

/// A class which mocks [Preview].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreview extends _i1.Mock implements _i13.Preview {
  @override
  _i11.Future<int> setSurfaceProvider() => (super.noSuchMethod(
        Invocation.method(
          #setSurfaceProvider,
          [],
        ),
        returnValue: _i11.Future<int>.value(0),
        returnValueForMissingStub: _i11.Future<int>.value(0),
      ) as _i11.Future<int>);
  @override
  void releaseFlutterSurfaceTexture() => super.noSuchMethod(
        Invocation.method(
          #releaseFlutterSurfaceTexture,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i11.Future<_i2.ResolutionInfo> getResolutionInfo() => (super.noSuchMethod(
        Invocation.method(
          #getResolutionInfo,
          [],
        ),
        returnValue:
            _i11.Future<_i2.ResolutionInfo>.value(_FakeResolutionInfo_0(
          this,
          Invocation.method(
            #getResolutionInfo,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i2.ResolutionInfo>.value(_FakeResolutionInfo_0(
          this,
          Invocation.method(
            #getResolutionInfo,
            [],
          ),
        )),
      ) as _i11.Future<_i2.ResolutionInfo>);
}

/// A class which mocks [ProcessCameraProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockProcessCameraProvider extends _i1.Mock
    implements _i14.ProcessCameraProvider {
  @override
  _i11.Future<List<_i10.CameraInfo>> getAvailableCameraInfos() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableCameraInfos,
          [],
        ),
        returnValue:
            _i11.Future<List<_i10.CameraInfo>>.value(<_i10.CameraInfo>[]),
        returnValueForMissingStub:
            _i11.Future<List<_i10.CameraInfo>>.value(<_i10.CameraInfo>[]),
      ) as _i11.Future<List<_i10.CameraInfo>>);
  @override
  _i11.Future<_i3.Camera> bindToLifecycle(
    _i12.CameraSelector? cameraSelector,
    List<_i15.UseCase>? useCases,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #bindToLifecycle,
          [
            cameraSelector,
            useCases,
          ],
        ),
        returnValue: _i11.Future<_i3.Camera>.value(_FakeCamera_1(
          this,
          Invocation.method(
            #bindToLifecycle,
            [
              cameraSelector,
              useCases,
            ],
          ),
        )),
        returnValueForMissingStub: _i11.Future<_i3.Camera>.value(_FakeCamera_1(
          this,
          Invocation.method(
            #bindToLifecycle,
            [
              cameraSelector,
              useCases,
            ],
          ),
        )),
      ) as _i11.Future<_i3.Camera>);
  @override
  void unbind(List<_i15.UseCase>? useCases) => super.noSuchMethod(
        Invocation.method(
          #unbind,
          [useCases],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void unbindAll() => super.noSuchMethod(
        Invocation.method(
          #unbindAll,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Recorder].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecorder extends _i1.Mock implements _i6.Recorder {
  @override
  set aspectRatio(int? _aspectRatio) => super.noSuchMethod(
        Invocation.setter(
          #aspectRatio,
          _aspectRatio,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set bitRate(int? _bitRate) => super.noSuchMethod(
        Invocation.setter(
          #bitRate,
          _bitRate,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i11.Future<_i4.PendingRecording> prepareRecording(String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #prepareRecording,
          [path],
        ),
        returnValue:
            _i11.Future<_i4.PendingRecording>.value(_FakePendingRecording_2(
          this,
          Invocation.method(
            #prepareRecording,
            [path],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i4.PendingRecording>.value(_FakePendingRecording_2(
          this,
          Invocation.method(
            #prepareRecording,
            [path],
          ),
        )),
      ) as _i11.Future<_i4.PendingRecording>);
}

/// A class which mocks [PendingRecording].
///
/// See the documentation for Mockito's code generation for more information.
class MockPendingRecording extends _i1.Mock implements _i4.PendingRecording {
  @override
  _i11.Future<_i5.Recording> start() => (super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValue: _i11.Future<_i5.Recording>.value(_FakeRecording_3(
          this,
          Invocation.method(
            #start,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i5.Recording>.value(_FakeRecording_3(
          this,
          Invocation.method(
            #start,
            [],
          ),
        )),
      ) as _i11.Future<_i5.Recording>);
}

/// A class which mocks [Recording].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecording extends _i1.Mock implements _i5.Recording {
  @override
  _i11.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> resume() => (super.noSuchMethod(
        Invocation.method(
          #resume,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
}

/// A class which mocks [VideoCapture].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoCapture extends _i1.Mock implements _i16.VideoCapture {
  @override
  _i11.Future<_i6.Recorder> getOutput() => (super.noSuchMethod(
        Invocation.method(
          #getOutput,
          [],
        ),
        returnValue: _i11.Future<_i6.Recorder>.value(_FakeRecorder_4(
          this,
          Invocation.method(
            #getOutput,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i6.Recorder>.value(_FakeRecorder_4(
          this,
          Invocation.method(
            #getOutput,
            [],
          ),
        )),
      ) as _i11.Future<_i6.Recorder>);
}

/// A class which mocks [BuildContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuildContext extends _i1.Mock implements _i7.BuildContext {
  MockBuildContext() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Widget get widget => (super.noSuchMethod(
        Invocation.getter(#widget),
        returnValue: _FakeWidget_5(
          this,
          Invocation.getter(#widget),
        ),
      ) as _i7.Widget);
  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);
  @override
  bool get debugDoingBuild => (super.noSuchMethod(
        Invocation.getter(#debugDoingBuild),
        returnValue: false,
      ) as bool);
  @override
  _i7.InheritedWidget dependOnInheritedElement(
    _i7.InheritedElement? ancestor, {
    Object? aspect,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #dependOnInheritedElement,
          [ancestor],
          {#aspect: aspect},
        ),
        returnValue: _FakeInheritedWidget_6(
          this,
          Invocation.method(
            #dependOnInheritedElement,
            [ancestor],
            {#aspect: aspect},
          ),
        ),
      ) as _i7.InheritedWidget);
  @override
  void visitAncestorElements(_i7.ConditionalElementVisitor? visitor) =>
      super.noSuchMethod(
        Invocation.method(
          #visitAncestorElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void visitChildElements(_i7.ElementVisitor? visitor) => super.noSuchMethod(
        Invocation.method(
          #visitChildElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispatchNotification(_i17.Notification? notification) =>
      super.noSuchMethod(
        Invocation.method(
          #dispatchNotification,
          [notification],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i9.DiagnosticsNode describeElement(
    String? name, {
    _i9.DiagnosticsTreeStyle? style = _i9.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeElement,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_7(
          this,
          Invocation.method(
            #describeElement,
            [name],
            {#style: style},
          ),
        ),
      ) as _i9.DiagnosticsNode);
  @override
  _i9.DiagnosticsNode describeWidget(
    String? name, {
    _i9.DiagnosticsTreeStyle? style = _i9.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeWidget,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_7(
          this,
          Invocation.method(
            #describeWidget,
            [name],
            {#style: style},
          ),
        ),
      ) as _i9.DiagnosticsNode);
  @override
  List<_i9.DiagnosticsNode> describeMissingAncestor(
          {required Type? expectedAncestorType}) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeMissingAncestor,
          [],
          {#expectedAncestorType: expectedAncestorType},
        ),
        returnValue: <_i9.DiagnosticsNode>[],
      ) as List<_i9.DiagnosticsNode>);
  @override
  _i9.DiagnosticsNode describeOwnershipChain(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeOwnershipChain,
          [name],
        ),
        returnValue: _FakeDiagnosticsNode_7(
          this,
          Invocation.method(
            #describeOwnershipChain,
            [name],
          ),
        ),
      ) as _i9.DiagnosticsNode);
}
